# Generated by Django 6.0.6 on 2026-07-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_libro_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo', models.CharField(choices=[('Estudiante', 'Estudiante'), ('Docente', 'Docente')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='libro',
            name='anio_publicacion',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='paginas',
        ),
        migrations.AddField(
            model_name='libro',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='isbn',
            field=models.CharField(default='Sin ISBN', max_length=20),
            preserve_default=False,
        ),
    ]
