# Generated by Django 6.0.6 on 2026-07-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuario_remove_libro_anio_publicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.CharField(default='Sin ISBN', max_length=20),
        ),
    ]
